### ISSUE TITLE
Descriptions for both student projects 

### ISSUE THREAD

**Issue by HowardCohl** [apsexton/bateman-ocr#2]
@apsexton In Readme.md there should be a description of both projects.
1. First give a title for each student project.
2. Then give a minor description for each student project.
3. Then assign the issue to the different students. I will assign both students to this task.  The more mathematically minded project should be assigned to Kevin Shen (I think this is clustering). The more computer science minded project should be assigned to Seong Joon Yoo (I think this is layout).

**Comment by apsexton** [comment]
I have done the first two. You need to add the students as collaborators (I think) and assign them

**Comment by HowardCohl** [comment]
@apsexton @LibriCerule @kevinshen100 

I think this issue has been completed having reviewed the Readme.md file.  

It might be possible to improve the description, but I think it's a very good start.
