### ISSUE TITLE
Getting started with the Layout project

### ISSUE THREAD

**Issue by apsexton** [apsexton/bateman-ocr#3]
The following is written in terms of using Eclipse. However, there is no requirement that Eclipse is used so please substitute any IDE that is supported by your environment.
1. Clone the repository
2. Set up your Eclipse environment
   - keep your repository clone in a different folder from your eclipse folder (see https://wiki.eclipse.org/EGit/User_Guide#Creating_Repositories for why, though you don't need to create a repository, just clone this one.)
   - Make sure you are using a recent Java JDK (e.g. 1.8 or later)
   - Make sure you are using a recent Eclipse (e.g Mars 1 Release 4.5.1 or later)
3. Set up the "layout" (and "gte" if you want) project in Eclipse
   1. Start Eclipse and make sure your workspace is different from (not contained in or containing) your repository folder
   2. File|Import|Git|Projects from Git... Select "Existing local repository" and add the local repository directory (bateman-ocr)
   3. Select Import existing Eclipse Projects" and "Next"
   4. At this point, it should show you the "gte" and "layout" projects. Select and them and finish.
   5. The Java perspective is probably not open so open it:
      - Window|Perspective|Open Perspective|Java
   6. Set your Run Configuration:
      1. Click on the drop down box beside the green run arrowhead in the top toolbar
      2. Run Configurations...
      3. Double click on Java Applications, set the name to "layout", Project to "layout" and click search to get the Main class (layout.main) and click "Apply"
      4. Make sure you can run the layout application by clicking on the green arrowhead.
   7. You may want to open the git perspective (Window|Perspective|Ope Perspective|Other...|Git) or just open the git repository and staging views (Windows|Show View|Other...|Git and select Git Repositories and Git Staging.
4. Familiarise yourself with the code, the Model/View/Controller structure, and specifically how actions work and are added to the menus, toolbars and have keyboard accelerators assigned

**Comment by HowardCohl** [comment]
@physikerwelt @apsexton @LibriCerule @kevinshen100 

I am just talking with Seong Joon.  He will be starting soon. (We will have to get his account setup). He was curious if he can just use a text editor and manual compilation instead of using eclipse, etc.

**Comment by apsexton** [comment]
I wouldn't like to forbid it outright, but I am afraid it would be a mistake. Getting up to speed on Eclipse or Intellij Idea (and I don't care which is used) will take a little time at the beginning - though not much if there is some assistance available at the lab - but the speed of software development in a plain text editor with no continuous compilation and syntax checking, Javadoc integration, code completion, code snippet generation, refactoring tools, debugger support etc.  would be  VERY much slower and more painful. It is for very good reason that modern professional Java development uses IDEs.

**Comment by physikerwelt** [comment]
I agree. I can post a guide for IntelliJ below, which you can just download and run locally (so you do not need to contact your admin).

**Comment by HowardCohl** [comment]
@LibriCerule Did you read the above posts?  I think they make a very convincing argument.

**Comment by LibriCerule** [comment]
Yup, I set up an Eclipse environment at home.

**Comment by LibriCerule** [comment]
@physikerwelt I would like to use Intellij for this project. Could you give me some advice here at NIST ASAP?
